apiVersion: v1
kind: Service
metadata:
  name: docker-desktop-loadbalancer
  namespace: <Your Release Name here>
spec:
  selector:
    "app.kubernetes.io/component": jenkins-controller
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
